# Generated by Django 3.0.8 on 2020-07-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_registrohoraextra_funcionatio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='funcionatio',
            new_name='funcionario',
        ),
    ]
